# Generated by Django 3.2.5 on 2022-04-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20220330_1202'),
        ('profiles', '0003_auto_20220216_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_campus_id', to='admission.campus'),
        ),
    ]
