# Generated by Django 3.2.5 on 2022-05-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='four_index',
        ),
        migrations.AddField(
            model_name='user',
            name='four_index',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
