# Generated by Django 3.2.5 on 2022-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220520_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='four_index',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
