# Generated by Django 3.2.5 on 2022-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_user_four_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='four_index',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
