# Generated by Django 3.2.5 on 2022-05-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gepg_pay_status', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=200, null=True)),
                ('control_number', models.CharField(blank=True, max_length=200, null=True)),
                ('trans_date', models.CharField(blank=True, max_length=50, null=True)),
                ('gepg_ack', models.CharField(blank=True, max_length=50, null=True)),
                ('index_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='billing.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='student',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id', to='billing.transactions'),
        ),
    ]
