# Generated by Django 3.2.5 on 2022-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20220112_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='choice_five',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice_four',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice_six',
        ),
        migrations.AddField(
            model_name='application',
            name='selected_programme',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
